// Code generated by scripts/gen-python-routine-samples-go.mjs from web/lib/pythonRoutineSamples.ts. DO NOT EDIT.

package seed

const growingSphereSource = `# Sample: growing sphere (REQ-032)
# A coloured sphere sits in the middle of the room and grows for 10 seconds.
# Lights inside the sphere turn on at full brightness with that colour.
# When the grow finishes, a new colour is picked and the sphere starts small again.
import math
import time

# Saved between runs — do not remove
if "_grow" not in globals():
    _grow = {"mode": "new"}

GROW_SEC = 10.0

if _grow["mode"] == "new":
    # New colour and geometry for this cycle
    _grow["colour"] = scene.random_hex_colour()
    _grow["cx"] = scene.width / 2
    _grow["cy"] = scene.height / 2
    _grow["cz"] = scene.depth / 2
    R = (
        math.hypot(
            scene.max_x - _grow["cx"],
            scene.max_y - _grow["cy"],
            scene.max_z - _grow["cz"],
        )
        + 1e-6
    )
    _grow["R"] = R
    # Start small but not zero (metres)
    _grow["r0"] = max(0.01, min(0.05, R * 0.02)) if R > 0.02 else R * 0.5
    _grow["t0"] = time.monotonic()
    _grow["mode"] = "grow"

if _grow["mode"] == "grow":
    elapsed = time.monotonic() - _grow["t0"]
    if elapsed >= GROW_SEC:
        # Done — next run will start a new colour
        _grow["mode"] = "new"
    else:
        r = _grow["r0"] + (_grow["R"] - _grow["r0"]) * (elapsed / GROW_SEC)
        await scene.set_lights_in_sphere(
            {"x": _grow["cx"], "y": _grow["cy"], "z": _grow["cz"]},
            r,
            {"on": True, "color": _grow["colour"], "brightness_pct": 100},
        )
`

const sweepingCuboidSource = `# Sample: sweeping cuboid (REQ-032)
# A thin slab (20 cm tall) covers the whole floor and slides up to the ceiling in 10 s.
# Lights inside the slab turn on with a random colour at full brightness.
# Lights that leave the slab are turned off. Then a new colour starts from the floor.
import time

if "_sweep" not in globals():
    _sweep = {"mode": "new"}

SWEEP_SEC = 10.0
SLAB_H = 0.2  # 20 cm in metres

if _sweep["mode"] == "new":
    _sweep["colour"] = scene.random_hex_colour()
    _sweep["w"] = scene.width
    _sweep["d"] = scene.depth
    _sweep["h"] = SLAB_H
    # Top position for the cuboid corner so the slab fits under the ceiling
    _sweep["y_top"] = max(0.0, scene.max_y - SLAB_H)
    _sweep["t0"] = time.monotonic()
    _sweep["prev"] = set()
    _sweep["mode"] = "sweep"

if _sweep["mode"] == "sweep":
    elapsed = time.monotonic() - _sweep["t0"]
    if elapsed >= SWEEP_SEC:
        # Turn off everyone who was still inside the slab at the top
        if _sweep["prev"]:
            await scene.update_lights_batch(
                [{"model_id": m, "light_id": lid, "on": False} for m, lid in _sweep["prev"]],
            )
        _sweep["prev"] = set()
        _sweep["mode"] = "new"
    else:
        y0 = _sweep["y_top"] * (elapsed / SWEEP_SEC)
        pos = {"x": 0.0, "y": y0, "z": 0.0}
        dim = {"width": _sweep["w"], "height": _sweep["h"], "depth": _sweep["d"]}
        inside = await scene.get_lights_within_cuboid(pos, dim)
        current = {(L["model_id"], L["light_id"]) for L in inside}
        await scene.set_lights_in_cuboid(
            pos,
            dim,
            {"on": True, "color": _sweep["colour"], "brightness_pct": 100},
        )
        exited = _sweep["prev"] - current
        if exited:
            await scene.update_lights_batch(
                [{"model_id": m, "light_id": lid, "on": False} for m, lid in exited],
            )
        _sweep["prev"] = current
`

const randomColourCycleSource = `# Sample: random colour cycle — all scene lights (REQ-032)
# Replaces the old server-side random_colour_cycle_all: ~1 s between full-scene recolours.
# Every light stays on at 100% brightness; each gets an independent random hex (REQ-030).
import time

if "_cycle" not in globals():
    _cycle = {"initialized": False, "last_tick": 0.0}

CYCLE_SEC = 1.0

if not _cycle["initialized"]:
    # Uniform on + starting colour so the whole scene is visible before we randomize
    await scene.set_all_lights(
        {"on": True, "color": "#ffffff", "brightness_pct": 100},
    )
    _cycle["initialized"] = True
    _cycle["last_tick"] = time.monotonic()

now = time.monotonic()
if now - _cycle["last_tick"] >= CYCLE_SEC:
    _cycle["last_tick"] = now
    lights = await scene.get_all_lights()
    updates = [
        {
            "model_id": L["model_id"],
            "light_id": L["light_id"],
            "on": True,
            "color": scene.random_hex_colour(),
            "brightness_pct": 100,
        }
        for L in lights
    ]
    if updates:
        await scene.update_lights_batch(updates)
`

// DefaultPythonRoutineRows returns the three REQ-032 definitions for store seeding (names, descriptions, python_source).
func DefaultPythonRoutineRows() [3]struct {
	Name        string
	Description string
	Source      string
} {
	return [3]struct {
		Name        string
		Description string
		Source      string
	}{
		{"Growing sphere (sample)", "REQ-032 novice sample: sphere grows 10 s in scene centre.", growingSphereSource},
		{"Sweeping cuboid (sample)", "REQ-032 novice sample: slab sweeps floor to ceiling.", sweepingCuboidSource},
		{"Random colour cycle — all lights (sample)", "REQ-032 novice sample: ~1 s full-scene random colours.", randomColourCycleSource},
	}
}
